### ISSUE TITLE
Who to notify is suboptimal when only a reviewer is present on the project

### ISSUE THREAD

**Issue by shiroyasha** [operately/operately#1039]
Example: On this project only Marko and me are working. Operately is offering me three options:

- To notify all the contributors (this makes sense)
- To select from a list, but I can't deselect Marko because he is the Reviewer
- To notify no one, but I can't (or shouldn't) really select this because the Reviewer will not be notified

![Screenshot 2024-09-03 at 13 37 56](https://github.com/user-attachments/assets/e6906bb5-455a-4c1c-9ce2-7383cf94a307)

**Comment by markoa** [comment]
Looks like in case when the project has only a champion or champion + reviewer, ie. no "regular" contributors, then this widget shouldn't be displayed at all?

**Comment by shiroyasha** [comment]
Yeah, sounds correct.
