### ISSUE TITLE
Subscription list: "No one" is misleading

### ISSUE THREAD

**Issue by shiroyasha** [operately/operately#1092]
A similar problem to this one (https://github.com/operately/operately/issues/1039), but not a direct match:

![Screenshot 2024-09-09 at 13 55 37](https://github.com/user-attachments/assets/ce5f907b-fdd9-47a1-a17a-96cf72ce1a65)

Operately offers me the option of "No one" which sounds like Operately won't notify no one even the reviewer, which is not true, as the reviewer is always notified.

**Comment by markoa** [comment]
This was solved in the meantime. Eg, when you go to post a discussion on a goal, you can't remove the champion and reviewer from the list of recipients: 

 ![Image](https://github.com/user-attachments/assets/15833f4b-0f39-4bcc-a292-451943620aaa)
