### ISSUE TITLE
In a confidential space, new project screen thinks everyone in the org can view it

### ISSUE THREAD

**Issue by markoa** [operately/operately#1185]
New project screen, within a confidential space:

<img width="651" alt="Screenshot 2024-09-25 at 13 15 17" src="https://github.com/user-attachments/assets/59bbe2f8-1131-4303-8641-2028dc9f6be8">

**Comment by shiroyasha** [comment]
Fix from the PR:
https://github.com/user-attachments/assets/83ffa053-a831-472c-a78f-a1d19089ab58
