### ISSUE TITLE
Saving Project Timeline decreases start and due dates by 1

### ISSUE THREAD

**Issue by Rockyy174** [operately/operately#1203]
Click on edit:
![1](https://github.com/user-attachments/assets/bdf99c93-6184-4755-ab71-2807c74525d8)

After saving it:
![2](https://github.com/user-attachments/assets/1bfc87ef-2013-4242-adc1-09530ccd8d41)

Click on edit again:
![3](https://github.com/user-attachments/assets/a45e0ba8-8706-44ea-9f6e-73b897ac7099)

After saving it again:
![4](https://github.com/user-attachments/assets/863eac65-1db3-4c2f-91f9-798ce878c5d5)

**Comment by shiroyasha** [comment]
Changing this to a bug as it is not just a minor nuisance, but something quite unexpected.

**Comment by Rockyy174** [comment]
I was investigating this bug and it seems that the problem happens when we parse the date:

https://github.com/operately/operately/blob/f05a125d69dd2a3f9c828c4704e5e5e089fa3af1/assets/js/utils/time.tsx#L84-L86

When I parsed the date `2024-09-21T00:00:00Z`, it became `Fri Sep 20 2024 21:00:00 GMT-0300 (Brasilia Standard Time)`. 

So, it seems that the 3-hour  difference is what is causing the day to change. Most likely, this bug will never appear for someone in Europe or somewhere where the time is later than GMT-0.

It should be quite easy to change the function so that it ignores the time zone when parsing the date. 
However, I'm afraid that there could be some side effects in the application if the function suddenly becomes unaware of time zones.

Do you think it's safe to change this function, @shiroyasha?

**Comment by shiroyasha** [comment]
Huh, hard question. :)

For parsing dates, it should be safe, but timezones are hard who knows what could be the side-effects. Any idea how we could get a guestimate about how safe this would be?

**Comment by Rockyy174** [comment]
For updating the project timeline, I can't think of any side-effects. The problem is that `parseISO` is used by `parse`, which is used in many places in the application. Personally, I think it would be quite unsafe to just change `parseISO`. 

I would rather create a new function which ignores the time zone or add a `ignoreTZ` flag to `parseISO`. 
Do you think it's a good approach?

**Comment by shiroyasha** [comment]
I agree. Sounds like a safer option
