### ISSUE TITLE
Wrong description for connecting projects to the goal

### ISSUE THREAD

**Issue by shiroyasha** [operately/operately#1207]
![Screenshot 2024-09-27 at 16 58 07](https://github.com/user-attachments/assets/d99ba88e-467b-45ed-b8ea-46d628d20cee)

Should be "[Actor] connected [Name] project to the goal".

assets/js/features/activities/ProjectGoalConnection/index.tsx

**Comment by SeanAverS** [comment]
Hi, 

Could I please be assigned this issue?

**Comment by shiroyasha** [comment]
Of course. Let me know if you need any help [setting up the development environment](https://github.com/operately/operately/blob/main/docs/dev-env.md), or with [opening a pull-request](https://github.com/operately/operately/blob/main/CONTRIBUTING.md).
