### ISSUE TITLE
Not clear what is a company goal any more

### ISSUE THREAD

**Issue by markoa** [operately/operately#1238]
Company space was recently renamed to "#{company.name} HQ" which propagated (almost) everywhere except:

<img width="397" alt="Screenshot 2024-10-02 at 16 02 49" src="https://github.com/user-attachments/assets/7abf461a-a8bf-4024-b225-b267655390d3">

company space is still called company space

but on the other hand:

<img width="287" alt="Screenshot 2024-10-02 at 16 03 36" src="https://github.com/user-attachments/assets/697107b7-f6f2-4187-9905-6e29d2eb5e3c">

when you look at a company-wide goal it feels like it's part of something else.

If we're keeping this "Company.name HQ" approach then we should find an alternative solution for the goals list.

**Comment by shiroyasha** [comment]
"If we're keeping this 'Company.name HQ' approach, then we should find an alternative solution for the goals list."

Just to clarify, this suggests that the change was made programmatically. However, I made this update manually via Space > Edit > Name to test if the main space can be renamed, not through code or some new default. New organizations will still receive the default "Company Space" name.

**Comment by markoa** [comment]
OK then I misunderstood. I wouldn't keep it as an open issue.

**Comment by shiroyasha** [comment]
Closing in that case.
