### ISSUE TITLE
Broken links in documentation for local installation

### ISSUE THREAD

**Issue by shiroyasha** [operately/operately#1247]

**Comment by markoa** [comment]
The report is about https://github.com/operately/operately/blob/main/docs/installation/local.md

I actually don't see the purpose of that page any more? IMO it's either [the official install instructions](https://operately.com/install/) if you wanna use it, or you set it up [for development](https://github.com/operately/operately/blob/main/docs/dev-env.md).

**Comment by shiroyasha** [comment]
This is the lowest cost of entry for anyone to try out Operately, it would be a shame to not have it. Self-hosted is close but not quite as it requires prep-work, while the dev version is not as convenient this "one liner".

Let's think about it over the weekend.
I'll remove the "bug" as it not a burning issue and remove the docs until we have an answer.
