### ISSUE TITLE
Email not working when a check-in is submitted for a project that doesn't have a reviewer

### ISSUE THREAD

**Issue by Rockyy174** [operately/operately#1274]
![img-1](https://github.com/user-attachments/assets/e145fcd0-ae0f-4e71-ab43-182e4c663514)

**Comment by markoa** [comment]
Is it still possible to trigger this scenario? If yes then let's mark it as a bug.

**Comment by Rockyy174** [comment]
I just tested it and the bug is still there. 

To trigger it, you just have to add contributors to a project that doesn't have a reviewer. Then, when you check in, the emails won't be sent and this error message will be visible in the console.
