### ISSUE TITLE
More elaborate descriptions of permissions

### ISSUE THREAD

**Issue by markoa** [operately/operately#1319]
<img width="641" alt="Screenshot 2024-10-11 at 14 47 47" src="https://github.com/user-attachments/assets/af6ccdcc-7f83-44b8-9815-cd8db2ff0269">

Introducing the small-print paragraph was a great idea. The proposal here is to use the opportunity to use the space to explain in a bit more detail and therefore educate on the fly users about what 'full', 'edit' etc mean.

Examples of the kind of sentences I have in mind:

For spaces:
- Everyone in the company will be able to view and comment on discussions, goals, and projects in this space.
- Everyone in the company will be able to view, comment, and create goals and projects in this space.
- (idk what full means but it would expand further, potentially may switch to 2-3 bullet points)

For projects:

example 1:
- Everyone in the company will be able to view and comment on this project
- Space members will be able to view, comment, check-in, manage team and roles.

example 2:
- Everyone in the company will be able to view this project
- Space members can view and comment in this project

**Comment by shiroyasha** [comment]
Adding a not here that when we add it, we should also change the popups on the access level badges:

![Screenshot 2024-10-11 at 15 04 08](https://github.com/user-attachments/assets/d0066b93-ee31-427a-a1ac-b913fff6d626)

**Comment by markoa** [comment]
Also there is a minor bug in space creation, when anyone on the internet can view we don't explain what company members can do regardless of what option is selected.

<img width="751" alt="Screenshot 2024-10-11 at 15 08 45" src="https://github.com/user-attachments/assets/02259eb6-16d7-431d-b4c6-b4be135b5b36">

**Comment by markoa** [comment]
Solved in the _Strengthening Privacy and People Management_ project.
