### ISSUE TITLE
Can't use text-base because of --color-base

### ISSUE THREAD

**Issue by markoa** [operately/operately#1327]
Having a color name defined like that

```css
body[data-theme="dark"] {
  --color-base: rgba(30, 30, 34, 1);
 ...
```

means that if we apply `text-base` class, which is a Tailwind for font size, we make the text the same color as the background color, ie. invisible.

**Comment by markoa** [comment]
There is a workaround, to set the class to `text-base/1`.

**Comment by shiroyasha** [comment]
Thinking out loud what would be a good replacement. This is the color of the background, semantically it would be something like:

```
--color-background-base
```

Here is what other software are using:

```
Basecamp: --color-body
Github: --color-canvas-default;
Todoist: --product-library-background-base-secondary
```

I like `--color-canvas-base` the most. It is a unique name that has very little chance to be confused with something else, or to clash with some predefined value.

**Comment by markoa** [comment]
Why are you looking elsewhere when you have already adopted the word `surface` :D 

<img width="935" alt="Screenshot 2024-10-15 at 10 41 13" src="https://github.com/user-attachments/assets/9b7f62fc-9492-42b5-a87b-80a0db02c0dd">

How about we rename what is currently `surface` to `surface-base` and rename `base` to `surface-background`? This is what they are in reality.

**Comment by shiroyasha** [comment]
Here `surface` == "color of the PaperContainer", so `surface-background` would imply the color of the paper, but you have a good point, `surface-background` could be as well interpreted as what is behind the paper.

Let's go with that one. Less new terms to learn.
