### ISSUE TITLE
File download sends files with hash IDs as file names instead of uploaded file names

### ISSUE THREAD

**Issue by markoa** [operately/operately#1366]
Expected human file names as uploaded, got this:

<img width="227" alt="Screenshot 2024-10-18 at 10 29 19" src="https://github.com/user-attachments/assets/ee977014-141d-4872-89f1-f49c4fc755db">

**Comment by shiroyasha** [comment]
The previous PR did not fix it. Seems like there is bug in the exaws library related to query params: https://github.com/ex-aws/ex_aws/issues/733.

Removing the content disposition part until I figure it out in this PR: https://github.com/operately/operately/pull/1391.
