### ISSUE TITLE
Comment box is displayed to users who don't have permissions to comment

### ISSUE THREAD

**Issue by Rockyy174** [operately/operately#1375]
No error is shown in the UI, so the user won't know why comments aren't working.

Trying to submit a comment:
![tmp1](https://github.com/user-attachments/assets/0cd7e74c-0e1a-4c55-bd10-da6341acedd4)

Error in the backend:
![tmp2](https://github.com/user-attachments/assets/ada3bda3-1e4d-436d-bc6d-2172421a9e20)

**Comment by markoa** [comment]
Comment box shouldn't be available to those who don't have the appropriate access level to comment.
