### ISSUE TITLE
Stuck review count

### ISSUE THREAD

**Issue by shiroyasha** [operately/operately#1395]
I often end up in this state:
https://github.com/user-attachments/assets/8536aa4a-df08-496d-801a-330c890fc87c

Here's what I recall happening:

- I received an email notification that @Rockyy174 submitted a check-in on a project where I'm a reviewer.
- I clicked "Acknowledge" in the email.
- I navigated through other screens, but the notification count stayed the same.
- When I did a hard refresh, the count reset to 0.

I'm marking this as a bug because it's not clear how to get the number back to 0 without refreshing, and the persistent notification gives me some serious OCD vibes until it's gone. 😅

---

### Proposal: Introducing a Failsafe

The signal to clear the notification can sometimes get lost due to an internet hiccup or a bug. To address this, we can implement a failsafe by triggering an ad-hoc recount each time the user visits the review page. This mechanism would ensure that the notification count is updated automatically, significantly reducing frustration for users who might otherwise feel stuck.

While this isn't a complete solution to the underlying issue, it’s a solid starting point. If we have this in place, we can convert the label from `bug` -> `papercut`.

**Comment by shiroyasha** [comment]
@Rockyy174 this was fixed with the Signals PR: https://github.com/operately/operately/pull/1406 right?

**Comment by Rockyy174** [comment]
Yes, I believe it was.

**Comment by shiroyasha** [comment]
Closing in that case.
