### ISSUE TITLE
Closed project list is not sorted by date

### ISSUE THREAD

**Issue by shiroyasha** [operately/operately#1404]
Project that you closed last week/last month are probably the most interesting ones on this screen. As they are not sorted by closed_at, they are all over the place, which makes the review of them unnecessary hard.

**Comment by shiroyasha** [comment]
I thought that it is a simple problem, but actually it might turn out to be more complex.
It seems that when we transitioned to a separated "project_retrospective" schema, we have also moved the `closed_at` timestamp to that schema.

But, we have several places where the application still relies on the `project.closed_at` timestamp. This was also one such case but I didn't realize it while fixing it https://github.com/operately/operately/issues/1379, this is the second place. We also need to check if email notification for check-ins don't rely on it.

@Rockyy174 how should we approach this problem?

1. If we keep the date only in the retrospective, then we would need to load the retro every time we load the project list, which might be inefficient.
2. If we update the date in two places, retro + project, we are duplicating data.
3. We can move it back to projects. So far I don't see major problems with that. This would also be helpful if we want to support a flow where someone closes, re-opens, and closes the project again where a project would have two retrospectives.

**Comment by Rockyy174** [comment]
Number 3. looks like the best solution to me. I don't see any specific why `closed_at` would have to be part of retrospectives. I think it may even make more sense if it's part of projects 🤔.

Are you already working on it, @shiroyasha ? Or would you like me to take care of it?

**Comment by shiroyasha** [comment]
I started working on this one: https://github.com/operately/operately/issues/1407, but it seems that we'll need it there as well https://github.com/operately/operately/pull/1416/files#diff-b8dde48c1c3bfba9d4d7ea125deddea5300878eeceadd056831a4231a9767050R109.

Please take this one over 🙏
