### ISSUE TITLE
Task assignee autocomplete selection is unreliable

### ISSUE THREAD

**Issue by markoa** [operately/operately#1439]
https://github.com/user-attachments/assets/2f112179-bba6-455f-a308-06b6b81d1102

**Comment by shiroyasha** [comment]
@markoa I'm struggling to reproduce it.

One way to move forward is to get more info from you: OS/Browser/Console logs/Plugins (e.g. LaspPass, OnePassowrd, Grammarly could interfere with the input).

Another way is for you to show me live.

**Comment by markoa** [comment]
Let's do it live by EOW. I use 1Password but disabling its Chrome add-on doesn't change the behavior; also nothing in JS console.

**Comment by shiroyasha** [comment]
The fix is shipped. However, as I was never able to fully reproduce it without making modifications to the code, I'm not a reliable tester if this functionality is truly fixed.

@markoa can you do the verification?

**Comment by markoa** [comment]
Great! I'm confirming it's good now.
