### ISSUE TITLE
Repeated avatars on the same page have the same key

### ISSUE THREAD

**Issue by Rockyy174** [operately/operately#1539]
![tmp](https://github.com/user-attachments/assets/ad6bb81d-88ec-4bc1-9a0e-8077255d95b5)

**Comment by Rockyy174** [comment]
Actually, there is such a project:
![tmp](https://github.com/user-attachments/assets/18ac4bf2-caee-4044-b9f6-a7843cbe0caa)

When this project is not displayed in the tree, I don't see the error in the console. 
My guess is that this project was created before https://github.com/operately/operately/issues/1424 was fixed. So, being assigned twice in a project shouldn't be possible any more 🤔

**Comment by shiroyasha** [comment]
Makes sense. In that case, I would close this issue.
