### ISSUE TITLE
Goals with no active projects have a chevron on goals & projects page

### ISSUE THREAD

**Issue by shiroyasha** [operately/operately#1559]
Example:

https://github.com/user-attachments/assets/493c5e05-7ab5-4fdd-9f8b-822459d0514d

The goal that I'm collapsing/expanding did have several projects, but all of them are completed at this point.

**Comment by markoa** [comment]
This happens (or is most obvious?) when you apply some filters which effectively "hide" some projects that would appear with the default view options.
