### ISSUE TITLE
Comment-on-goal-update notification redirects to broken page

### ISSUE THREAD

**Issue by Rockyy174** [operately/operately#1673]
I've just received a notification saying the someone commented on a goal update, but when I clicked on the notification, I got a 500. In the console, I can see that the `GetGoalProgressUpdate` query is returning a 404.

I think the notification is redirecting to the wrong path. I'm not 100% sure, but by looking at the URL, it seems I'm redirected to `.../goal-updates/{goal_id}` instead of `.../goal-updates/{goal_update_id}`

**Comment by shiroyasha** [comment]
I wanted to report the same just now. Ditto.
