### ISSUE TITLE
Show comment count on space Discussions list

### ISSUE THREAD

**Issue by markoa** [operately/operately#1723]
we show it here on home:
<img width="382" alt="Screenshot 2024-12-13 at 13 08 00" src="https://github.com/user-attachments/assets/5197fada-0d76-4810-925a-74944e4a5d97" />

but not here:
<img width="1068" alt="Screenshot 2024-12-13 at 13 08 16" src="https://github.com/user-attachments/assets/32903305-7e5c-4ffa-8df7-dbd0a82b7e91" />

**Comment by shiroyasha** [comment]
Implemented here: https://github.com/operately/operately/pull/1790.
