### ISSUE TITLE
Docs & Files widget: Display thumbnail if it exists 

### ISSUE THREAD

**Issue by markoa** [operately/operately#1739]
The idea is to have consistent presentation. Here for example the images would be represented with the thumbnail which already exists, instead of this generic icon:

<img width="365" alt="Screenshot 2024-12-18 at 15 57 47" src="https://github.com/user-attachments/assets/308d307e-7024-47eb-a632-4ae8f3757016" />

**Comment by shiroyasha** [comment]
Fixed https://github.com/operately/operately/pull/1786.
