### ISSUE TITLE
Space: Buttons on zero-state tools lead to the root page of the tool

### ISSUE THREAD

**Issue by markoa** [operately/operately#1768]
Saw this in our org in prod.

**Comment by shiroyasha** [comment]
This is by design, as there is no clear action to take when you click on the button. I've changed the title to include all tools.

**Comment by markoa** [comment]
I mean the button leads to `/` the absolute root of the whole app. The illustration leads correctly to the docs & files "root".

**Comment by shiroyasha** [comment]
Oh, wow. That's completely different. Hard bug.
