### ISSUE TITLE
Add 🫡 saluting emoji to reaction list

### ISSUE THREAD

**Issue by markoa** [operately/operately#445]
This is my most frequently used emoji therefore it has to be included in the list. 😁

For real though it's great for saying "ACK" in a neutral way. None of these works like that:

![Screenshot 2024-05-08 at 11 06 34](https://github.com/operately/operately/assets/1779493/fe640a26-d4ef-4ed4-9f1f-701e884a0a03)

**Comment by Ayush9026** [comment]
Screenshot is not visible @markoa sir.

**Comment by shiroyasha** [comment]
@Ayush9026 thanks for the heads up. It seems that the screenshot got lost when I transfered it to this repository.

**Comment by Ayush9026** [comment]
@markoa sir will i have to add only saluting emojis or all most frequently used emoji.

**Comment by Ayush9026** [comment]
Please tell sir @markoa and @shiroyasha sir will i have to add only saluting emojis or all most frequently used emoji.

**Comment by shiroyasha** [comment]
Saluting emoji added in https://github.com/operately/operately/pull/546.
For now, we just replaced an existing emoji that was kind off a duplicate. In the future we might expand the list.
