### ISSUE TITLE
Space feed not showing activities

### ISSUE THREAD

**Issue by markoa** [operately/operately#514]
Noticed this on our staging instance, where for example in Marketing space latest activity is very old:

<img width="209" alt="Screenshot 2024-06-05 at 15 46 12" src="https://github.com/operately/operately/assets/8651/7aef2b99-d04f-4b80-8e1d-c2b58587a216">

whereas we do have a newer project with some activity (the conference project).

**Comment by shiroyasha** [comment]
Found the source of the problem. 

Project activities such as project check-in and project creation are not marked with the space ID, so they don't show up in the space feed.

To fix it, we should:

1. Add the space_id markings
2. Retroactively fill-in space_id markings for old activities

**Comment by shiroyasha** [comment]
Extending the problem with what @marko reported:

> Comments on discussions do not appear in the space / company feed
