### ISSUE TITLE
Tests not working if server is running

### ISSUE THREAD

**Issue by Rockyy174** [operately/operately#531]
After https://github.com/operately/operately/pull/500, tests don't work if the server is running.

Currently, the solution to the problem is run `./devenv down` and `./devenv up` to stop and start the containers. Although this solution works, it's a bit cumbersome and slows down development, especially when writing tests for the UI.

![tests-not-working](https://github.com/operately/operately/assets/80377510/11256cf6-26ba-4bae-95d2-885b40d7c53d)

**Comment by shiroyasha** [comment]
I've tested it on my local computer, and the clash is no longer present.
I'm closing this, but @Rockyy174 if you still notice this bug after this PR was merged, please feel free to reopen.

**Comment by Rockyy174** [comment]
Yes, everything seems to be working well now, @shiroyasha.
