### ISSUE TITLE
Person mentioned should be completed to a shortened, not full name

### ISSUE THREAD

**Issue by markoa** [operately/operately#590]
This is unnecessary and adds a weird dose of formality as in an old Russian novel:

<img width="440" alt="Screenshot 2024-06-18 at 13 51 12" src="https://github.com/operately/operately/assets/8651/37afe34e-6948-4fdf-bfc3-593a0f77bcb1">

**Comment by Rockyy174** [comment]
@markoa In the example above, should the name be converted to "Christian" or "Christian S.G.A"? Or should it be something else?

**Comment by markoa** [comment]
@Rockyy174 Good question. Should be "Christian S."

Btw, imo the best UX is avatar + first name only. But if it's an order of magnitude more complex then we shoudl stick to text only and in that case it's as above.
