### ISSUE TITLE
Don't allow goal champion and reviewer to be the same person

### ISSUE THREAD

**Issue by markoa** [operately/operately#591]
There are no circumstances under which this will lead to positive outcomes.

<img width="411" alt="Screenshot 2024-06-18 at 13 57 50" src="https://github.com/operately/operately/assets/8651/6d7a8e7d-462c-4f78-8872-afa891a0f7b6">

**Comment by markoa** [comment]
It looks like the app allows the same for projects atm.

**Comment by markoa** [comment]
I'd like to explore a potential solution where
- it's not possible for the champion and reviewer to be the same person
- so if you're working alone, you may define a goal without a reviewer
- but then there is no check-in / acknowledge feedback loop, and this is marked as a big warning

**Comment by markoa** [comment]
Here's how it would work then:
- When creating a project, you cannot select yourself, and it is possible to not select anyone as a reviewer.
- Check-ins work, you are prompted weekly, but no one is being prompted to ack.
- There are signs on the collaborator list in project header and in the check-in section that it's quite important to have a reviewer.

project header:

![Image](https://github.com/user-attachments/assets/a37ee6b8-76bd-41ae-b038-1c73a9083f58)


check-in area:
![Image](https://github.com/user-attachments/assets/25e4a90b-9254-40cc-b507-1018d2271e8f)

---

If we agree with this, we can mirror the same behavior on goals.

**Comment by shiroyasha** [comment]
Implemented in the above PRs.
