### ISSUE TITLE
Goals hierarchy: paused projects are displayed without any indicator

### ISSUE THREAD

**Issue by markoa** [operately/operately#597]
imo it's a good idea to show them just find it confusing when there is no indicator hinting which project is paused.

**Comment by markoa** [comment]
I keep getting confused by paused projects as I review things so here's a suggestion for a first step with some color-coding:

<img width="1121" alt="Screenshot 2024-06-25 at 12 41 29" src="https://github.com/operately/operately/assets/8651/d641304d-5bca-4da0-a3d9-12d6a158a20b">

if `project.paused?`
- all text in the row would be grey
- project icon would not be blue but also grey
- progress bar would not be filled with green (if it has any progress) but a dark grey
- in the popup that appears when clicking on the progress bar, we can say instead of "XX% Complete" → "PAUSED - XX% Complete" and again not use green for those letters but dark grey.

**Comment by shiroyasha** [comment]
Reopening as I've noticed today that it is not solved. 
Currently, paused projects are not listed.

**Comment by markoa** [comment]
@shiroyasha wdym? I see a paused project when I set the filter.
<img width="326" alt="Screenshot 2024-11-13 at 18 32 22" src="https://github.com/user-attachments/assets/45c183e1-4de6-4eab-9846-5243cddd38bd">

**Comment by shiroyasha** [comment]
Heh, completely my mistake. I didn't expect it to be hidden by default, nor did I check the settings. We can close it.
