### ISSUE TITLE
Rename project "progress" indicator

### ISSUE THREAD

**Issue by markoa** [operately/operately#622]
I think we were never super confident that progress is the right word for this. Came across a project like this:

<img width="722" alt="Screenshot 2024-06-21 at 10 20 07" src="https://github.com/operately/operately/assets/8651/d823d8ac-6454-40c5-b5f2-fa7ae21514bb">

My proposal is to rename this to "Time spent" and give it a soft red background color if the project is beyond the deadline.

**Comment by shiroyasha** [comment]
If we are on this topic we can also expand to make the whole line a bit clearer.
I don't have a specific idea just putting it on the table.

The first two are super clear, `start date` and `due date`, but `duration` and `progress` (even when we rename it to time spent) is murky.

**Comment by shiroyasha** [comment]
What do you think about this:

```
Start Date   Due Date    Time Spent 
Apr 9        May 15      10 weeks (5w overdue)
```

If the due date is not set:

```
Start Date   Due Date    Time Spent 
Apr 9        Not Set     10 weeks
```

If the duration is less than 14 days:

```
Start Date   Due Date    Time Spent 
Apr 9        Not Set     11 days
```

**Comment by markoa** [comment]
I wouldn't remove "duration" because it's not feasible to compute in your head how much time you have given two random dates.

**Comment by shiroyasha** [comment]
Good point. I removed it because it is somewhat ambiguous what is duration. Do we maybe have a better word for it? 🤔

Something that is clear like "time budget", "allocated days", but is not two words?

**Comment by markoa** [comment]
Exploration of a view with progress bar indicating if time-wise we're OK or not. (Operately not giving hints when things are obviously not OK is one of my biggest gripes rn.)

<img width="677" alt="Screenshot 2024-06-21 at 11 13 23" src="https://github.com/operately/operately/assets/8651/c8995799-7275-475d-b5b6-e232d843da9b">

**Comment by markoa** [comment]
Not 100% relevant and we might be changing this UI completely so I want to log this here.

This is a project that was completed in two days:
<img width="813" alt="Screenshot 2024-07-25 at 13 16 06" src="https://github.com/user-attachments/assets/05d177c8-fdd5-4259-9b05-61dd80bf557f">

So after a project is closed, if we are communicating "Duration" anywhere then that should be the actual duration and not estimated.

**Comment by markoa** [comment]
here's another approach that that would keep things simple:

while the project is running, display "countdown" (colored red when overdue):
<img width="442" alt="Screenshot 2024-08-08 at 15 26 55" src="https://github.com/user-attachments/assets/b46598d5-9b10-499e-9968-6ba3128dd28e">

after the project has been completed, display when it was completed and how that compares with schedule:
<img width="520" alt="Screenshot 2024-08-08 at 15 27 51" src="https://github.com/user-attachments/assets/2d9de40a-12cd-469a-968d-56690e728af1">
