### ISSUE TITLE
Company administration screen after creating a self-hosted account is unaware of the company admin

### ISSUE THREAD

**Issue by markoa** [operately/operately#641]
This is what the screen looks like after going through the local setup:

<img width="1030" alt="Screenshot 2024-06-26 at 13 16 22" src="https://github.com/operately/operately/assets/8651/5b684d26-502e-4fe2-9603-5a6f275a08ad">

Expected:
- myself under "Administrators"
- The admin actions to add people etc

**Comment by Rockyy174** [comment]
Did this happen after using the new "first-time-setup", @markoa? 

If yes, I remember fixing it some time ago while I was working on the security model. It should be working correctly now.

**Comment by markoa** [comment]
Yes, new "first-time-setup" by creating myself a user account in terminal...

**Comment by shiroyasha** [comment]
Tested it today, this is no longer the case. It was fixed in the security project.

![Screenshot 2024-08-05 at 16 46 48](https://github.com/user-attachments/assets/c473b7ef-aed3-4a29-865a-30bef082e817)
