### ISSUE TITLE
Who will be notified indicator

### ISSUE THREAD

**Issue by markoa** [operately/operately#663]
[Don't make me think](https://en.wikipedia.org/wiki/Don%27t_Make_Me_Think) principle. Will be useful pretty much anywhere you write something and click send.

Selecting / unselected people from the list would be a great next step but doesn't have to be done in the first pass.

We implemented this for project Check-Ins to validate the approach.

For other actions like Goal Check-Ins, Comments, Discussions, it is a todo.

**Comment by Rockyy174** [comment]
We have successfully added this feature to project check-ins, goal updates, discussions and project retrospectives.
