### ISSUE TITLE
Project creation: simplify permission selection

### ISSUE THREAD

**Issue by markoa** [operately/operately#769]
The introduction of a permission model has made the project creation screen unnecessarily complicated imo.

1/ The default choice rn is "Secret" -- it is not in the spirit of transparency that we advocate to recommend this as the default. "Internal" would be more appropriate.

2/ Labels -- I'd like to discuss the possibility of using more humane labels on this screen such as "Space-restricted" instead of "Confidential" and "Exclusive" instead of "Secret".

3/ Access Levels drop downs 🤯 
- 3.1/ Showing them by default brings instant decision fatigue. I'd hide them, but make them available behind a link.
- 3.2/ "Has full access", "Can edit" -- can't expect a normal human to understand this (at least I don't). We should come up with more descriptive labels in the UI. 
- 3.3/ IMO the default for "Everyone in $(space)" should be "Can Comment"; a blanket block on communication is not a productive choice.

**Comment by shiroyasha** [comment]
implemented here: https://github.com/operately/operately/pull/1132.
