### ISSUE TITLE
Reviews are not ordered by date

### ISSUE THREAD

**Issue by shiroyasha** [operately/operately#789]
Noticed this when trying out the feature in prod:

![Screenshot 2024-07-25 at 18 12 13](https://github.com/user-attachments/assets/8cd79c9e-b9cf-4f92-953f-6a0421ab72e2)

**Comment by Rockyy174** [comment]
Wow, I didn't come across this during development. There is code that is supposed to sort them. 
Also, I can't understand why "Dec 15, 2023" decided to be formatted differently :sob:

Could you show me what `get_assignments` is returning to you? 

e.g:
![tmp](https://github.com/user-attachments/assets/f6404ea4-0bee-40ca-997d-2dfee0445acb)

**Comment by shiroyasha** [comment]
I've already acknowledged them, so I can't show you the API response. Sorry.

The change from `Dec 15` to `Dec 15, 2023` is built into the FormattedTime component if you have used it. The logic is that for dates in the current year it will show a short date, but for dates from previous years it will also add the year to avoid date confusion.

**Comment by shiroyasha** [comment]
I might have a clue where does the problem come from: lib/operately_web/api/queries/get_assignments.ex:30. Comparing dates with `>` is not a correct comparison for Elixir dates.

More info: https://www.elixirstreams.com/tips/comparing-elixir-datetimes-and-dates

**Comment by Rockyy174** [comment]
Cool. Most likely that is the issue.

**Comment by shiroyasha** [comment]
TBH I'm not even sure why is `<` `>` for structs as it will almost always lead to the wrong result. Most likely there is a historic reason why this is allowed.

**Comment by Rockyy174** [comment]
:sweat_smile:
