### ISSUE TITLE
Bad contrast for notification bubble on Notifications and Reviews

### ISSUE THREAD

**Issue by shiroyasha** [operately/operately#790]
I remember having an issue for this for the notification bubble but it probably got lost in the transition. Opening a new one.

![Screenshot 2024-07-25 at 18 18 39](https://github.com/user-attachments/assets/6cc903a9-9cd4-4b8c-9f3c-e208ee5fc574)

**Comment by Rockyy174** [comment]
This is how it looks in the dark theme. It seems that white contrasts better with red than black.
What do you think about making it white for the light theme as well?

![tmp](https://github.com/user-attachments/assets/08964b5b-aa0b-4eab-bb80-c0c23ab19a6f)

**Comment by shiroyasha** [comment]
It seems much better. Let's use that one.
