### ISSUE TITLE
Project's next check-in scheduled for "Invalid date"

### ISSUE THREAD

**Issue by Rockyy174** [operately/operately#802]
In the Project's page, the next check-in date is shown as "Invalid date".

![bug-next-check-in](https://github.com/user-attachments/assets/82fafd87-da26-4b1b-9e36-6c8940fc932e)

**Comment by markoa** [comment]
Saw this one today too:
<img width="648" alt="Screenshot 2024-08-02 at 14 51 51" src="https://github.com/user-attachments/assets/1e0df8a5-19ab-42ae-8f0e-6b4c8681cb0e">
