### ISSUE TITLE
One view of goals and projects

### ISSUE THREAD

**Issue by markoa** [operately/operately#809]
Currently in top navigation and spaces we have "Goals", which shows a hierarchy of goals and projects, and "Projects" as separate views.

This ticket is about designing a v2 unified view of goals and projects that would eliminate the need for a separate projects screen.

Accomplishing this would not only simplify navigation but further strengthen the idea that work should always be associated with outcomes.

**Comment by Rockyy174** [comment]
Already implemented https://github.com/operately/operately/pull/1474.
