### ISSUE TITLE
Review page: Wrong person on the item

### ISSUE THREAD

**Issue by shiroyasha** [operately/operately#826]
Item:

![Screenshot 2024-08-02 at 15 04 08](https://github.com/user-attachments/assets/a5216dff-38ab-426e-86b3-01a21fc80ee7)

When I click on it:

![Screenshot 2024-08-02 at 15 05 20](https://github.com/user-attachments/assets/cf9db783-57d1-48b3-9f41-db71c19faaed)

**Comment by markoa** [comment]
source for view should be author of actual check-in not current project champion
