### ISSUE TITLE
Data migrations are manual and hard to track

### ISSUE THREAD

**Issue by shiroyasha** [operately/operately#834]
Data migrations, located in `lib/operately/data/change_*` are currently hard to manage. 

Problems:

- Not clear which data migrations are executed in prod, staging, and on various self-hosted installations

- In development environments there is no notification that you need to run them, e.g. Marko pulls the latest changes from main and he gets no clue from the system that there are pending data migrations which are blockers for further development

- No automation around them, they are executed manually by system admins which is error prone and slows down development

**Comment by markoa** [comment]
Can't see a solution that doesn't involve opening a ticket. That would have a checklist of all places.

**Comment by markoa** [comment]
I see, makes sense!
