### ISSUE TITLE
Removing yourself as owner or reviewer shouldn't remove you from the project

### ISSUE THREAD

**Issue by markoa** [operately/operately#850]
So there was this project where I was the owner and then transferred the champion role to someone else.

After I've done that I was not able to do anything on the project.

I'd expect that the app would automatically keep me as a regular project member.

**Comment by shiroyasha** [comment]
Let's add this to the access level batch as well.

If you are a company owner / space manager, this is papercut level. For everyone else, this is serious headache on private projects as there is no easy way to change your role without losing access to the project.

**Comment by shiroyasha** [comment]
Implemented in https://github.com/operately/operately/pull/1113.
