### ISSUE TITLE
Email sent to wrong person

### ISSUE THREAD

**Issue by Rockyy174** [operately/operately#867]
I think this problem's cause is the same as in https://github.com/operately/operately/issues/826.

Email I've received:
![1](https://github.com/user-attachments/assets/ffa60bae-3afd-4596-a34b-7e6377b0f283)

Another person is the author of the check-in:
![2](https://github.com/user-attachments/assets/02262e2d-c39f-447c-adf5-2f377e7ce329)

**Comment by markoa** [comment]
Closing assuming it was resolved with what resolved the above mentioned issue.
