### ISSUE TITLE
Project page needs an indicator of privacy level

### ISSUE THREAD

**Issue by markoa** [operately/operately#966]
We now have four levels privacy, which [will be rephrased](https://github.com/operately/operately/issues/769).

Once a project is live, the privacy level is quite hidden, as the only way to see it is to open the ellipsis menu > Edit project permissions.

The best solution would be for the project page to include an indicator, which could potentially be a button that opens up permission settings, similar to how it works in Google Docs. And also in the [(new) goals & projects hierarchy](https://github.com/operately/operately/issues/809).

**Comment by markoa** [comment]
At the last meeting we came up with the idea to:
- add an icon at the end of the project title, based on the privacy level
  - globe if the project is public
  - no icon if it's the default (available to all organization members)
  - lock icon if "all people in space"
  - dark(?) icon if "only those who are invited"
  - tooltip (a sentence in active voice) on icon
- change the button "Manage team" to "Manage team & access", expand the scope of the subsequent screen accordingly

This feels both intuitive and simple enough.

**Comment by shiroyasha** [comment]
I discussed this one with Marko in a bit more detail on Friday. The current best idea is to have indicators as a continuation of the name of the resource.

We would use the following equivalent in the names:

1. 🌐 for public resources
2. No icon for default ones
3. 🔒 for confidential
4. 🔒 (red) for exclusive projects

When you hover over these icons, a popup would give you further context.

**Comment by shiroyasha** [comment]
Heh @markoa we were writing at the same time.
