### ISSUE TITLE
One command to rebuild everything for local development

### ISSUE THREAD

**Issue by markoa** [operately/operately#970]
After #968 I ran into an issue of having outdated JS packages. Typically I shut down the dev server and run `make up && make dev.up && make dev.server` but this time this did not solve the issue. @shiroyasha advised to run `make dev.shell && cd assets && npm install`, after which I had to re-run the three previously mentioned commands.

Ideally we'd have one command to full-stack rebuild the dev environment instead of several seemingly overlapping but incomplete commands.

**Comment by shiroyasha** [comment]
Thinking out loud about the appropriate names. 

@Rockyy174 wdyt about:

1. Build your development environment:

```
make dev.build
```

Which would build docker, start it, install mix deps, install npm deps, create databases, run migrations. This command would also take care of "rebuilds".

2. Starts the development server:

```
make dev.server
```

**Comment by Rockyy174** [comment]
Those names are intuitive and easy to remember in my opinion.
